spring:
  application:
    name: microservice-gateway-server           # 指定要注冊到Eureka Server上的應用程式之名稱
  http:
    multipart:
      enabled: true   # 啟用http上傳
      max-file-size: 200MB # 設置單文件的最大長度
      max-request-size: 200MB # 設置最大的請求文件之大小
      file-size-threshold: 2MB  # 當上傳檔案到達2MB時, 寫入磁碟
      location: /  # 上傳檔案的臨時目錄
      
server:
  port: 8080                                    # 指定這台Server啟動的port