spring:
  application:
    name: microservice-gateway-server           # 指定要注冊到Eureka Server上的應用程式之名稱
  http:
    multipart:
      enabled: true   # 啟用http上傳
      max-file-size: 300MB # 設置單文件的最大長度
      max-request-size: 300MB # 設置最大的請求文件之大小
      file-size-threshold: 30MB  # 當上傳檔案到達2MB時, 寫入磁碟
      location: data/tmp  # 上傳檔案的臨時目錄
  jackson: 
    default-property-inclusion: NON_NULL
  cloud:
    config:
      name: eureka-client-setting
      uri: http://localhost:8888/     # 這種直接指定IP的方式並不優雅,當你有兩台以上Config Server時,也不會做到load balanced,下面方法較優
      profile: default                # 本地檔案,無GIT,用default沒差 
server:
  port: 8080                                    # 指定這台Server啟動的port