spring:
  application:
     name: microservice-config-server
  profiles:
     active: native                     # 本地檔案,無GIT
  cloud:
    config:
      server:
        native:
          search-locations: file:D:/MyWork/DataIntegrationService/BackEndMileStone/Mircoservice-Properties  #本地檔案,無GIT,直接指定一個你想存放各個微服務之property檔的位置
server:
  port: 8888                            # 此Config Server Process啟動的port
eureka:
  client:
    serviceUrl:                                                 # http://localhost:8761/eureka/,表示用戶或微服務要與Eureka Server溝通的地址,默認即為左顯示,若有多個Eureka Server地址可以用逗號隔開
      defaultZone: http://leoliu:mypass@localhost:8761/eureka/  # 若Eureka Server有設定基本認證時,需加上"帳號:密碼"的格式
  instance:
    prefer-ip-address: true                                     # 是否把自己的ip註冊到Eureka Server上,若為false表示會註冊此微服務所在電腦的hostname到Eureka Server上
management:
  security:
    enabled: false                      # 把安全性關掉,這裡是方便測試