spring:
  application:
    name: backend-trinity-repository         # 在eureka server的應用程式名稱
  http:
    multipart:
      enabled: true   # 啟用http上傳
      max-file-size: 300MB # 設置單文件的最大長度
      max-request-size: 300MB # 设置最大的请求文件的大小
      file-size-threshold: 30MB  # 設置最大的請求文件之大小
  jackson: 
    default-property-inclusion: NON_NULL
server:
  port: 9001                                 # Process啟動的port
  tomcat:
    basedir: ./
encrypt:
  key: trinity