spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: org.eclipse.persistence.platform.database.PostgreSQLPlatform
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/trinity
    username: trinity
    password: trinity
    tomcat:
      max-active: 20
      initial-size: 5
      max-wait: 10000
logging: 
  level: 
    org: 
      springframework: 
        jdbc: 
          core: 
            JdbcTemplate: debug