spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false           #Hibernate嘗試驗證PostgreSQL的CLOB特性，但是PostgreSQL的JDBC驅動並沒有實現這個特性 
  datasource:
    platform: org.eclipse.persistence.platform.database.PostgreSQLPlatform
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/trinity113
    username: trinity
    password: trinity
    tomcat:
      max-active: 20
      initial-size: 5
      max-wait: 10000
logging: 
  level: 
    org: 
      springframework: 
        jdbc: 
          core: 
            JdbcTemplate: debug